image: openjdk:8

stages:
  - build
  - test

before_script:
  - chmod +x gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew --build-cache assemble
  artifacts:
    paths:
      - 'minecraft/bukkit/build/libs/*-dist.jar'
      - 'minecraft/fabric/build/libs/*-dist.jar'
      - 'minecraft/forge/build/libs/*-dist.jar'
    expire_in: 1 week
#  only:
#    - master

test:
  stage: test
  script:
    - ./gradlew check
